---
# Creating the rack monitoring setup.
- hosts: uky
:wq
  roles:
    - fabric_prometheus

  #vars_files:  use --extra-var="your var file name"

  vars:
    install_type: geni_slice
    extra_node_hosts: {}
