
# The node exporters are installed directly on the nodes with systemd enabled.
# To enable TLS, there needs to be a cert installed. Self-signed certs are generally used since
#    most nodes do not have certs and they are only used to encrypt the data, not ensure who the 
#    host is.
# The node export listens to the ip:host set in the node_exporter_web_listen_address var.

- name: Install Node Exporter Certs
  include_tasks: NodeExporter/node_exporter_certs_tasks.yml

- name: Install Node Exporter
  include_role: 
    name: cloudalchemy.node_exporter
  
