---


# OK
##############################
#  Fabric Rack Prometheus    #
##############################
- name: Install Fabric-Prometheus setup 
  block:
  - name: Install Fabric Rack
    import_tasks: fabric_rack_install_tasks.yml
    when: component_type == 'head'
  when: 
    - install_type is defined
    - install_type == 'standard_fabric_rack'


# OK
##############################
#  Node Exporter Install     #
##############################
- name: Install node_exporter 
  # need each node to have node_exporter
  block:
  - name: Install Node_exporter
    import_tasks: install_node_exporter_tasks.yml
    when: 
      - component_type == 'head' or component_type == 'worker'
  when: 
    - install_type is defined
    - install_type == 'standard_fabric_rack' 


# ##############################
# # Worker Node Docker System   #
# ##############################
# #docker - should be already there
# #docker network -need to add
# #nginx - need to add
# #docker monitor - need to add

# - name: Install worker node network and proxy nginx 
#   # need each worker node to have docker network and nginx 
#   # to proxy things without TLS or auth
#   block:
#   - name: Install worker docker network
#     import_tasks: worker_node_tasks.yml
#     when: 
#       component_type == 'worker'
#   when: 
#     - install_type is defined
#     - install_type == 'standard_fabric_rack' 



# ##############################
# #     Docker Exporter        #
# ##############################
# - name: Install worker node docker monitoring 
#   # need each worker node to have docker network and exporter
#   block:
#   - name: Install worker docker monitoring
#     import_tasks: monitored_node_tasks.yml
#     when: 
#       component_type == 'worker'
#   when: 
#     - install_type is defined
#     - install_type == 'standard_fabric_rack' 

# OK
##############################
# Setup VPN Ping Configs     #
##############################
- name: Setup VPN configs 
  block:
  - name: Setup Promtheus Config Files
    include_tasks: Prometheus/add_prometheus_config_templates.yml
    # Just copies the one template to the Promtheus config.
    # Note assumes the prometheus_templates_dir has been set in vars file.
    vars:
      prometheus_config_template_files:
        - vpn_ping_targets.yml
  when: 
    - install_type is defined
    - install_type == 'standard_fabric_rack' 
    - component_type == 'head'
    - set_vpn_pings is defined
    - set_vpn_pings



##############################################################
#                       GENI Slice                           #
##############################################################
# This section contains the tasks needed for installing 
# Prometheus on a GENI Slice. 
# Use the var install_type: geni_slice to trigger these tasks.
# To control the sub tasks define the add_ variables
#   add_docker: yes  
#     Adds docker and docker-compose install.
#   add_monitor: yes
#     Adds the main Prometheus components - Prometheus, Grafana
#     etc.. on the monitoring node.
#   add_node_exporter: yes 
#     Adds the node_exporter to a node.

- name: GENI Slice
  block:
  ###############################
  #   GENI Slice Prereqs        #
  ###############################

  # These tasks may be required on nodes that do not have docker already installed.
  - name: Install Docker 
    become: yes
    import_tasks: install_docker_tasks.yml
    when: 
      - add_docker is defined
      - add_docker

  - name: Install python sdk to manage docker
    become: yes
    import_tasks: install_docker_python_sdk_tasks.yml
    when: 
      - add_python_docker_sdk is defined
      - add_python_docker_sdk


  ###############################
  #   GENI Slice Prometheus     #
  ###############################
  - name: Install Prometheus setup on a GENI Slice 
    block:
    - name: Install GENI Rack
      import_tasks: geni_slice_install_tasks.yml
    when: 
      - add_monitor is defined
      - add_monitor 
      
  ###############################
  #   Node Exporter Install     #
  ###############################
  - name: Install node_exporter for GENI rack
    # need each node to have node_exporter
    block:
    - name: Install Node_exporter
      import_tasks: install_node_exporter_tasks.yml
      when: 
        - yes
    when: 
      - add_node_exporter is defined
      - add_node_exporter 

  when: 
      - install_type is defined
      - install_type == 'geni_slice' 

##############################################################
#                   end GENI Slice                           #
##############################################################



