--- 

- hosts: "{{ variable_hosts | default('x')}} "

  vars: 
    base_install_dir: /opt/fabric_prometheus
  tasks:
    - name: Stop docker compose on head node
      block:
      
        - name: Stop fabric-prometheus docker compose
          community.docker.docker_compose:
            project_src: '{{base_install_dir}}'
            state: absent
          register: down_output

        - ansible.builtin.debug:
            var: down_output
      become: yes
      when: component_type=="head"
