--- 
 
- hosts: "{{ variable_hosts | default('x')}}"

  vars: 
    base_install_dir: /opt/fabric_prometheus
  tasks:

    - name: Start docker compose on head node
      block:
        - name: Start fabric-prometheus docker compose
          community.docker.docker_compose:
            project_src: '{{base_install_dir}}'
            state: present
          register: up_output

        - ansible.builtin.debug:
            var: up_output
      become: yes
      when: component_type=="head"
