---
- hosts: localhost
  tasks:

  - name: Create local tmp directory
    file:
      path: ./tmp
      state: directory

  - name: Clone the fabric-deployment repository.
    git:
      repo: https://github.com/fabric-testbed/fabric-deployment.git
      dest: ./tmp/fabric-deployment-repo

  - name: Copy the needed dirs and files
    block:
      - name: Create working dir
        file:
          path: ./tmp/working
          state: directory

      - name: Copy needed files.
        copy:
          src: ./tmp/fabric-deployment-repo/fabric-ansible/{{item}}
          dest: ./tmp/working/
          
        with_items:
          - group_vars
          - host_vars
          - fabric-hosts

  - name: Remove the no longer needed fabric-deployment repository.
    file: 
      path: ./tmp/fabric-deployment-repo
      state: absent

        